# Project information
site_name: Network Learning
theme:
  name: material
  logo: assets/logo.png
  features:
    - navigation.tabs
    - navigation.instant
site_url: https://squidfunk.github.io/mkdocs-material/
site_author: Christian Rose
site_description: >-
  Write your documentation in Markdown and create a professional static site in
  minutes – searchable, customizable, in 60+ languages, for all devices

# Repository
repo_name: DenDanskeMine/Network-learning
repo_url: https://github.com/DenDanskeMine/Network-learning
edit_uri: edit/main/docs/
# Copyright
copyright: Copyright &copy; 2023 - 2024 Christian Rose

# Configuration
theme:
  name: material

  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    #- navigation.expand
    - navigation.footer
     - navigation.indexes
     - navigation.instant
     - navigation.instant.prefetch
     - navigation.instant.progress
     - navigation.prune
   #  - navigation.sections
    - navigation.tabs
    - navigation.top
   #  - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    #- toc.follow
   # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      scheme: auto
      primary: indigo
      accent: indigo
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo

  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'




# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/squidfunk
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/squidfunk/mkdocs-material/
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/mkdocs-material/
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@squidfunk
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/squidfunk

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: dendanskemine
      repo: network-learning
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


# Page tree

nav:
  - Hjem: index.md
  - Introduktion: intro.md
  - Cisco Grundlæggende:
    - Netværkskonfiguration: grundlaeggende-konfiguration.md
    - Netværkstopologier: grundlaeggende-topologier.md
    - Netværksenheder: grundlaeggende-enheder.md
    - Netværksprotokoller: grundlaeggende-protokoller.md
  - Cisco Mellemniveau:
    - Routing: mellemniveau-routing.md
    - Switching: mellemniveau-switching.md
    - VLANs: mellemniveau-vlans.md
    - STP: mellemniveau-stp.md

  - Avanceret:
    - Netværkssikkerhed: avanceret-sikkerhed.md
    - Firewalls: firewalls.md